{% set name = "sicor" %}
{% set version = "0.20.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sicor-{{ version }}.tar.gz
  sha256: 71167d863fb28d57a6458ece3ecee81d1170c67f02e7adb427c60e0b9a33adae


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - arosics >=1.2.4
    - cachetools
    - cdsapi
    - cerberus
    - dicttoxml
    - dill
    - ecmwf-api-client
    - gdal
    - gdown
    - geoarray >=0.8.17
    - glymur
    - h5py
    - isofit >=2.10
    - iso8601
    - jsmin
    - libgdal-jp2openjpeg
    - matplotlib-base
    - mpld3
    - netcdf4
    - numba
    - numpy
    - numpy-indexed
    - openpyxl
    - pandas
    - pillow
    - pint
    - psutil
    - pygrib
    - pyprind
    - pyproj
    - pyrsr
    - pytables
    - python >={{ python_min }}
    - py-tools-ds >=0.14.12
    - requests
    - scikit-image >=0.20.0
    - scikit-learn <=1.2.2  # due to https://git.gfz-potsdam.de/EnMAP/sicor/-/issues/107
    - scipy
    - spectral
    - sympy
    - tqdm
    - xlrd

test:
  imports:
    - sicor
    - sicor.AC.RtFo
    - sicor.AC.RtFo_3_phases
    - sicor.ECMWF
    - sicor.Mask
    - sicor.tables
    - sicor.Tools
    - sicor.sicor
    - sicor.sicor_ac
    - sicor.sicor_enmap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.gfz-potsdam.de/EnMAP/sicor
  summary: Sensor Independent Atmospheric Correction
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklasbohn
    - danschef
