{% set name = "sicor" %}
{% set version = "0.20.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sicor-{{ version }}.tar.gz
  sha256: c90964b93c97ff0a452826fb60d7bb41729db2892bff78ab025c6c657458099c


build:
  entry_points:
    - sicor_ac = sicor.cli.sicor_ac:main
    - sicor_ecmwf = sicor.cli.sicor_ecmwf:main
    - sicor_ac_EnMAP = sicor.cli.sicor_ac_EnMAP:main
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - arosics >=1.2.4
    - cachetools
    - cdsapi
    - cerberus
    - dicttoxml
    - dill
    - ecmwf-api-client
    - gdal
    - gdown
    - geoarray >=0.8.17
    - glymur
    - h5py
    - isofit >=2.10
    - iso8601
    - jsmin
    - libgdal-jp2openjpeg
    - matplotlib-base
    - mpld3
    - netcdf4
    - numba >=0.63  # https://github.com/conda-forge/llvmlite-feedstock/issues/109
    - numpy
    - numpy-indexed
    - openpyxl
    - pandas
    - pillow
    - pint
    - psutil
    - pygrib
    - pyprind
    - pyproj
    - pyrsr
    - pytables
    - python >={{ python_min }}
    - py-tools-ds >=0.14.12
    - requests
    - scikit-image >=0.20.0
    - scikit-learn
    - scipy
    - spectral
    - sympy
    - tqdm
    - xlrd

test:
  imports:
    - sicor
    - sicor.AC.RtFo
    - sicor.AC.RtFo_3_phases
    - sicor.ECMWF
    - sicor.Mask
    - sicor.tables
    - sicor.Tools
    - sicor.sicor
    - sicor.sicor_ac
    - sicor.sicor_enmap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://git.gfz.de/EnMAP/sicor
  summary: Sensor Independent Atmospheric Correction
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danschef
    - unbohn
